In [166]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as pl

In [167]:
custdirty = pd.read_csv("C:/Uner/Semester 4/Data Mining I/Week 3/custdirty_data.csv")

In [168]:
custdirty.isna().sum()

ID                        0
CustomerID              514
Product_Category       1309
Purchase_Date             0
Price                     0
Quantity                765
Product_Description       0
Country                   0
Phone_Number              0
Email                     0
dtype: int64

In [169]:
def clean_phone(phone):
        phone = re.sub(r'\D', '', str(phone))  
        return phone if len(phone) >= 10 and len(phone) <= 12 else "Unknown/Invalid Format"   # Pastikan panjangnya valid

custdirty["Phone_Number"] =custdirty["Phone_Number"].apply(clean_phone)

In [170]:
custdirty['Phone_Number'].head(100)

0                 2505181271
1     Unknown/Invalid Format
2     Unknown/Invalid Format
3     Unknown/Invalid Format
4                 2942836286
               ...
95                9492164819
96                6496001839
97    Unknown/Invalid Format
98    Unknown/Invalid Format
99                5122415172
Name: Phone_Number, Length: 100, dtype: object

In [171]:
hospital = pd.read_csv("C:/Uner/Semester 4/Data Mining I/Week 3/hospital_data_dirty.csv")

In [172]:
government = pd.read_csv("C:/Uner/Semester 4/Data Mining I/Week 3/government_citizenship_dirty.csv")

In [173]:
custdirty

,ID,CustomerID,Product_Category,Purchase_Date,Price,Quantity,Product_Description,Country,Phone_Number,Email
0,1,CUST_001,Electronics,Mar 05 2024,65.58,11.0,"Today, federal, claim, report, consider, publi...",USA,2505181271,eric82@example.com
1,2,CUST_002,Electronics,May 29 2024,335.85,1.0,Alone appear example.,Canada,Unknown/Invalid Format,allentodd@example.org
2,3,CUST_003,Electronics,May 28 2024,106.92,19.0,"DIRECTION, SECURITY, WHO, GROUND, TRIP, ROOM. ...",United Kingdom,Unknown/Invalid Format,oschultz@example.com
3,4,CUST_004,Clothing,Jun 30 2024,389.70,6.0,"Answer, huge, six, new, tough. - picture",Canada,Unknown/Invalid Format,ajohnson@example.org
4,5,CUST_005,Furniture,14/10/2024,140.78,14.0,Recent last economic establish understand.,Canada,2942836286,andersonsheriexample.org.
...,...,...,...,...,...,...,...,...,...,...
10295,7431,CUST_7431,Furniture,Feb 24 2024,445.08,6.0,"Meeting, adult, choose, customer, see, base. -...",USA,Unknown/Invalid Format,erinleon@example.net
10296,940,CUST_940,Clothing,Jun 13 2024,188.90,9.0,Actually home blue get.,Usa,Unknown/Invalid Format,obrienmichael@example.org
10297,9519,CUST_9519,Clothing,Apr 04 2024,371.88,NaN,Option stand determine course include.,Usa,4348959812,brownjames@example.net
10298,1804,CUST_1804,Books,May 06 2024,165.60,18.0,"ACCOUNT, AFFECT, NIGHT. - ATTACK",CAN,8682519899,thomas86@example.com
10299,8721,CUST_8721,Clothing,2024-08-12,90.66,4.0,"Fall, task, vote, remain, my, score. - toward",Usa,Unknown/Invalid Format,kyle30@example.org

In [174]:
hospital

,PatientID,AdmissionDate,DischargeDate,Diagnosis,Treatment,Doctor,Department,Age,Gender,BloodType,Medication,TestResults,BillingAmount,InsuranceProvider,AppointmentDate
0,PT_001,10/3/2024,5/11/2025,Appendicitis,"Special with job,",Carl Beard,Orthopedics,81,Female,B+,NaN,85/67,9495.73,NaN,2/17/2024
1,PT_K_2,6/27/2023,12/5/2023,Fracture,"Certainly way ten,",Mary Sanchez,Endo,-88,M,O-,civil,140/118,8681.08,HC Insurance,8/8/2023
2,PT_003,5/18/2024,4/29/2025,Appendicitis,"Study small,",Mr. Patrick Harris MD,Orthopedics,94,M,O-,word,92/95,2829.42,NaN,5/21/2024
3,PT_004,Mar 11 1978,10/26/2019,COPD,"Investment human,",Donald Roach,Endocrinology,26,F,A+,NaN,140/119,1121.27,NaN,11/3/2024
4,PT_005,11/23/2024,12/2/2024,Diabetes,"Every coach,",NaN,Ortho,35,Female,B-,NaN,71/68,5555.75,HC Insurance,11/14/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10295,PT_691,3/16/2024,NaN,COPD,"Focus population green,",Jennifer Rodriguez,Cardio,68,Female,O+,step,High,5014.95,HealthPlus,4/21/2024
10296,PT_7247,3/29/2023,10/27/2024,Fracture,"Hold,",Christine Morris,Ortho,15,F,O-,floor 1 units,98/68,8152.91,NaN,12/14/2023
10297,PT_4814,Oct 11 1998,4/22/2005,Fracture,"Imagine power PM,",Luis May,Endocrinology,3,Male,A+,senior,181/80,2323.13,NaN,6/13/2024
10298,PT_8633,2/1/2024,11/28/2024,Dyabetes,"Morning body than,",Jamie King,Cardiology,52,M,AB+,NaN,169/46,3466.39,HealthPlus,6/26/2024
10299,PT_2977,Mar 31 2017,2/1/2018,COPD,"Notice after staff,",Thomas Perry,Cardilogy,89,U,A+,edge,72/46,5592.93,MediCare,1/24/2024

In [175]:
government

,CitizenID,Name,BirthDate,Nationality,Address,VotingStatus,PassportNumber,TaxID,MaritalStatus,CriminalRecord,EducationLevel,Income,ImmigrationYear
0,CIT_001,Allen Novak,1968-06-16,USA,"597 Carr Creek Apt. 464; West Andrew; NE 76236,",No,460200468,NaN,Married,No,HS,42533.54,NaN
1,CIT_002,TAMARA RAMSEY,1987-02-11,FRANCE,"3899 Medina Roads; Crystaltown; NY 04112,",No,INVALID_our,TAX-002-36,S,No,Masters,28175.78,NaN
2,CIT_003,David Williams,1937-12-15,Bharat,"03064 Eric Ferry; Port Rebecca; AZ 09961,",Y,E48182721,TAX-003-03,Widowed,,High School,143299.35,1986.0
3,CIT_004,Desiree Willis,1991-03-24,USA,"773 Perry Flats; East Michael; WY 77221,",Y,O98365870,TAX_004_11,Married,No,Doctorate,105629.33,NaN
4,CIT_005,Terry Gill,2000-10-15,FR,"214 Michael Crescent Suite 393, New Paulport, ...",N,R72171677,TAX-005-00,S,Pending,PhD,117985.07,2005.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10495,CIT_3673,Scott Barrett,1950-03-08,IND,"10041 Fisher Row Suite 135, Lake Anneburgh, GA...",N,407208444,NaN,Unknown,,PhD,99415.01,NaN
10496,CIT_8693,JAMES BROWN,2000-12-13,US,"563 Romero Ferry, Petersonport, OR 06511",N,983829316,TAX-8693-20,Unknown,NaN,PhD,128327.81,NaN
10497,CIT_7140,Susan Beck,2001-05-11,US,"31275 Michelle Well Suite 725, West Randytown,...",,INVALID_enjoy,TAX-7140-50,Single,Yes,High School,26909.17,NaN
10498,CIT_779,JACKSON STOUT,1983-08-18,India,"10300 Michelle Passage, Amandaburgh, RI 93986",Registered,O91186652,TAX-779-15,S,No,High School,132278.13,1969.0
10499,CIT_2923,DAWN LANE,2002-12-23,United States,"07158 Tamara Drives Apt. 970, Brooksfurt, CT 3...",No,S29245729,TAX-2923-67,Married,Yes,PhD,52938.39,NaN

### Prepo Data Custdirty

In [176]:
custdirty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10300 entries, 0 to 10299
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   10300 non-null  int64
 1   CustomerID           9786 non-null   object
 2   Product_Category     8991 non-null   object
 3   Purchase_Date        10300 non-null  object
 4   Price                10300 non-null  float64
 5   Quantity             9535 non-null   float64
 6   Product_Description  10300 non-null  object
 7   Country              10300 non-null  object
 8   Phone_Number         10300 non-null  object
 9   Email                10300 non-null  object
dtypes: float64(2), int64(1), object(7)
memory usage: 804.8+ KB

In [177]:
custdirty.nunique()

ID                     10000
CustomerID              9501
Product_Category           7
Purchase_Date           1098
Price                   8891
Quantity                  19
Product_Description    10000
Country                    7
Phone_Number            3615
Email                   9831
dtype: int64

In [178]:
custdirty['Country'].value_counts()

Country
United Kingdom    1751
UK                1716
CAN               1677
Canada            1668
usa               1197
Usa               1164
USA               1127
Name: count, dtype: int64

In [179]:
df_cleaned.nunique()

ID                     10000
CustomerID             10000
Product_Category           7
Purchase_Date            406
Price                   8891
Quantity                  19
Product_Description    10000
Country                    3
Phone_Number            3615
Email                   9831
dtype: int64

In [180]:
custdirty['Product_Category'].value_counts()

Product_Category
Grocery        1363
Furniture      1344
Sports         1339
Electronics    1322
Books          1309
Clothing       1308
Electornics    1006
Name: count, dtype: int64

In [181]:
import re
from sklearn.impute import KNNImputer

def preprocess_data(df):
    # 1. Memperbaiki format tanggal
    def fix_date(date):
        try:
            return pd.to_datetime(date, infer_datetime_format=True, dayfirst=True).strftime('%d-%m-%Y')
        except Exception:
            return None

    df["Purchase_Date"] = df["Purchase_Date"].apply(fix_date)

    # 2. Memperbaiki format nomor telepon
    def clean_phone(phone):
        phone = re.sub(r'\D', '', str(phone))  
        return phone if len(phone) >= 10 and len(phone) <= 12 else "Unknown/Invalid Format"   # Pastikan panjangnya valid

    df["Phone_Number"] = df["Phone_Number"].apply(clean_phone)

    # 3. Mengisi kolom "CustomerID" dengan "CUST_{df['ID']}"
    df["CustomerID"] = df["ID"].apply(lambda x: f"CUST_{x}")

    # 4. Memperbaiki format negara
    df['Country'] = df['Country'].apply(
    lambda x: "United Kingdom" if str(x).strip().lower() in ["united kingdom", "uk"] else
                "United States" if str(x).strip().lower() in ["united states", "usa", "us"] else 
                "Canada" if str(x).strip().lower() in ["canada", "can"] else x)

    df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
    imputer = KNNImputer(n_neighbors=5)
    df[['Quantity']] = imputer.fit_transform(df[['Quantity']])
    df['Quantity'] = df['Quantity'].round().astype(int)

    df["Product_Category"] = df["Product_Category"].fillna("Unknown/Undifined")
    df['Product_Category'] = df['Product_Category'].apply(
    lambda x: "Electronics" if str(x).strip().lower() in ["electronics", "electornics"] else x)

    return df

# Preprocess data
df_cleaned = preprocess_data(custdirty)

# Display first few rows after preprocessing
df_cleaned.info()

C:\Users\Faiz Iqbal\AppData\Local\Temp\ipykernel_32284\264419238.py:8: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  return pd.to_datetime(date, infer_datetime_format=True, dayfirst=True).strftime('%d-%m-%Y')
C:\Users\Faiz Iqbal\AppData\Local\Temp\ipykernel_32284\264419238.py:8: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(date, infer_datetime_format=True, dayfirst=True).strftime('%d-%m-%Y')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10300 entries, 0 to 10299
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   10300 non-null  int64
 1   CustomerID           10300 non-null  object
 2   Product_Category     10300 non-null  object
 3   Purchase_Date        10300 non-null  object
 4   Price                10300 non-null  float64
 5   Quantity             10300 non-null  int64
 6   Product_Description  10300 non-null  object
 7   Country              10300 non-null  object
 8   Phone_Number         10300 non-null  object
 9   Email                10300 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 804.8+ KB

In [182]:
df_cleaned

,ID,CustomerID,Product_Category,Purchase_Date,Price,Quantity,Product_Description,Country,Phone_Number,Email
0,1,CUST_1,Electronics,05-03-2024,65.58,11,"Today, federal, claim, report, consider, publi...",United States,2505181271,eric82@example.com
1,2,CUST_2,Electronics,29-05-2024,335.85,1,Alone appear example.,Canada,Unknown/Invalid Format,allentodd@example.org
2,3,CUST_3,Electronics,28-05-2024,106.92,19,"DIRECTION, SECURITY, WHO, GROUND, TRIP, ROOM. ...",United Kingdom,Unknown/Invalid Format,oschultz@example.com
3,4,CUST_4,Clothing,30-06-2024,389.70,6,"Answer, huge, six, new, tough. - picture",Canada,Unknown/Invalid Format,ajohnson@example.org
4,5,CUST_5,Furniture,14-10-2024,140.78,14,Recent last economic establish understand.,Canada,2942836286,andersonsheriexample.org.
...,...,...,...,...,...,...,...,...,...,...
10295,7431,CUST_7431,Furniture,24-02-2024,445.08,6,"Meeting, adult, choose, customer, see, base. -...",United States,Unknown/Invalid Format,erinleon@example.net
10296,940,CUST_940,Clothing,13-06-2024,188.90,9,Actually home blue get.,United States,Unknown/Invalid Format,obrienmichael@example.org
10297,9519,CUST_9519,Clothing,04-04-2024,371.88,10,Option stand determine course include.,United States,4348959812,brownjames@example.net
10298,1804,CUST_1804,Books,06-05-2024,165.60,18,"ACCOUNT, AFFECT, NIGHT. - ATTACK",Canada,8682519899,thomas86@example.com
10299,8721,CUST_8721,Clothing,08-12-2024,90.66,4,"Fall, task, vote, remain, my, score. - toward",United States,Unknown/Invalid Format,kyle30@example.org

# Prepo Hospital

In [183]:
hospital.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10300 entries, 0 to 10299
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PatientID          10300 non-null  object
 1   AdmissionDate      10300 non-null  object
 2   DischargeDate      7248 non-null   object
 3   Diagnosis          10300 non-null  object
 4   Treatment          10300 non-null  object
 5   Doctor             9241 non-null   object
 6   Department         10300 non-null  object
 7   Age                10300 non-null  int64
 8   Gender             10300 non-null  object
 9   BloodType          10300 non-null  object
 10  Medication         6149 non-null   object
 11  TestResults        10300 non-null  object
 12  BillingAmount      10300 non-null  float64
 13  InsuranceProvider  6615 non-null   object
 14  AppointmentDate    10300 non-null  object
dtypes: float64(1), int64(1), object(13)
memory usage: 1.2+ MB

In [184]:
hospital.isna().sum()

PatientID               0
AdmissionDate           0
DischargeDate        3052
Diagnosis               0
Treatment               0
Doctor               1059
Department              0
Age                     0
Gender                  0
BloodType               0
Medication           4151
TestResults             0
BillingAmount           0
InsuranceProvider    3685
AppointmentDate         0
dtype: int64

In [185]:
hospital.nunique()

PatientID            10000
AdmissionDate         2051
DischargeDate         1350
Diagnosis               13
Treatment             9679
Doctor                8489
Department               7
Age                    193
Gender                   5
BloodType               10
Medication            2664
TestResults           5993
BillingAmount         9676
InsuranceProvider        4
AppointmentDate        731
dtype: int64

In [186]:
hospital.nunique()

PatientID            10000
AdmissionDate         2051
DischargeDate         1350
Diagnosis               13
Treatment             9679
Doctor                8489
Department               7
Age                    193
Gender                   5
BloodType               10
Medication            2664
TestResults           5993
BillingAmount         9676
InsuranceProvider        4
AppointmentDate        731
dtype: int64

In [187]:
hospital["Doctor"] = hospital["Doctor"].fillna("Unknown/Undifined")
hospital["Medication"] = hospital["Medication"].fillna("Unknown/Undifined")
hospital["InsuranceProvider"] = hospital["InsuranceProvider"].fillna("Unknown/Undifined")
hospital["DischargeDate"] = hospital["DischargeDate"].fillna("Unknown/Undifined")

In [188]:
hospital['BloodType'].value_counts()
hospital['Age'] = hospital['Age'].abs()

In [189]:
hospital['Diagnosis'].value_counts()

Diagnosis
Fracture        1894
COPD            1842
Appendicitis    1664
Diabetes        1607
Hypertension    1602
diabetes         228
Appendycytys     220
Dyabetes         212
hypertension     211
fracture         209
copd             208
appendicitis     203
Hypertensyon     200
Name: count, dtype: int64

In [190]:
hospital['Diagnosis'] = hospital['Diagnosis'].apply(
    lambda x: "Hypertension" if str(x).strip().lower() in ["hypertension", "hypertensyon"] else
                "COPD" if str(x).strip().lower() in ["copd"] else 
                "Fracture" if str(x).strip().lower() in ["fracture"] else 
                "Appendicitis" if str(x).strip().lower() in ["appendicitis", "appendycytys"] else 
                "Diabetes" if str(x).strip().lower() in ["diabetes", "dyabetes"] else x
)

In [191]:
hospital['Department'].value_counts()

Department
Endocrinology    1762
Orthopedics      1755
Ortho            1721
Endo             1687
Cardio           1148
Cardiology       1126
Cardilogy        1101
Name: count, dtype: int64

In [192]:
hospital['Department'] = hospital['Department'].apply(
    lambda x: "Orthopedics" if str(x).strip().lower() in ["orthopedics", "ortho"] else
                "Endocrinology" if str(x).strip().lower() in ["endocrinology", "endo"] else
                "Cardiology" if str(x).strip().lower() in ["cardiology", "cardilogy", "cardio"] else x)

In [193]:
hospital['BloodType'].value_counts()

BloodType
B+            1051
A positive    1051
O-            1045
A-            1036
AB+           1033
A+            1030
O+            1030
AB-           1018
B negative    1005
B-            1001
Name: count, dtype: int64

In [194]:
blood_type_mapping = {
    "A positive": "A+", "A negative": "A-",
    "B positive": "B+", "B negative": "B-",
    "O positive": "O+", "O negative": "O-",
    "AB positive": "AB+", "AB negative": "AB-"
}

# Fungsi untuk mengonversi format
def convert_blood_type(blood_type):
    return blood_type_mapping.get(blood_type, blood_type)  # Jika tidak ditemukan, kembalikan nilai aslinya

# Terapkan perubahan pada kolom "BloodType"
hospital["BloodType"] = hospital["BloodType"].astype(str).apply(convert_blood_type)

# Menampilkan hasil setelah konversi
hospital["BloodType"].value_counts()

BloodType
A+     2081
B-     2006
B+     1051
O-     1045
A-     1036
AB+    1033
O+     1030
AB-    1018
Name: count, dtype: int64

In [195]:
import re
from sklearn.impute import KNNImputer

def preprocess_data2(df):
    
    def fix_date(date):
        try:
            return pd.to_datetime(date, infer_datetime_format=True, dayfirst=True).strftime('%d-%m-%Y')
        except Exception:
            return None

    df["AdmissionDate"] = df["AdmissionDate"].apply(fix_date)
    df["DischargeDate"] = df["DischargeDate"].apply(fix_date)
    df["AppointmentDate"] = df["AppointmentDate"].apply(fix_date)

    df['Gender'] = df['Gender'].apply(
    lambda x: "Female" if str(x).strip().lower() in ["female", "f"] else
                "Male" if str(x).strip().lower() in ["male", "m"] else 
                "Unknown/Undifined" if str(x).strip().lower() in ["unknown", "u"] else x)

    df['Department'] = df['Department'].apply(
    lambda x: "Orthopedics" if str(x).strip().lower() in ["orthopedics", "ortho"] else
                "Endocrinology" if str(x).strip().lower() in ["endocrinology", "endo"] else
                "Cardiology" if str(x).strip().lower() in ["cardiology", "cardilogy", "cardio"] else x)
    
    df['Diagnosis'] = df['Diagnosis'].apply(
    lambda x: "Hypertension" if str(x).strip().lower() in ["hypertension", "hypertensyon"] else
                "COPD" if str(x).strip().lower() in ["copd"] else 
                "Fracture" if str(x).strip().lower() in ["fracture"] else 
                "Appendicitis" if str(x).strip().lower() in ["appendicitis", "appendycytys"] else 
                "Diabetes" if str(x).strip().lower() in ["diabetes", "dyabetes"] else x)
    
    df["Doctor"] = df["Doctor"].fillna("Unknown/Undifined")
    df["Medication"] = df["Medication"].fillna("Unknown/Undifined")
    df["InsuranceProvider"] = df["InsuranceProvider"].fillna("Unknown/None")
    df["DischargeDate"] = df["DischargeDate"].fillna("Unknown/Undifined")
    
    df['Age'] = df['Age'].abs()

    blood_type_mapping = {
        "A positive": "A+", "A negative": "A-",
        "B positive": "B+", "B negative": "B-",
        "O positive": "O+", "O negative": "O-",
        "AB positive": "AB+", "AB negative": "AB-"
    }

    # Fungsi untuk mengonversi format
    def convert_blood_type(blood_type):
        return blood_type_mapping.get(blood_type, blood_type)  # Jika tidak ditemukan, kembalikan nilai aslinya

# Terapkan perubahan pada kolom "BloodType"
    df["BloodType"] = df["BloodType"].astype(str).apply(convert_blood_type)

    return df

# Preprocess data
df_cleaned2 = preprocess_data2(hospital)

# Display first few rows after preprocessing
df_cleaned2.info()

C:\Users\Faiz Iqbal\AppData\Local\Temp\ipykernel_32284\1951640726.py:8: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  return pd.to_datetime(date, infer_datetime_format=True, dayfirst=True).strftime('%d-%m-%Y')
C:\Users\Faiz Iqbal\AppData\Local\Temp\ipykernel_32284\1951640726.py:8: UserWarning: Parsing dates in %m/%d/%Y format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(date, infer_datetime_format=True, dayfirst=True).strftime('%d-%m-%Y')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10300 entries, 0 to 10299
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PatientID          10300 non-null  object
 1   AdmissionDate      10300 non-null  object
 2   DischargeDate      10300 non-null  object
 3   Diagnosis          10300 non-null  object
 4   Treatment          10300 non-null  object
 5   Doctor             10300 non-null  object
 6   Department         10300 non-null  object
 7   Age                10300 non-null  int64
 8   Gender             10300 non-null  object
 9   BloodType          10300 non-null  object
 10  Medication         10300 non-null  object
 11  TestResults        10300 non-null  object
 12  BillingAmount      10300 non-null  float64
 13  InsuranceProvider  10300 non-null  object
 14  AppointmentDate    10300 non-null  object
dtypes: float64(1), int64(1), object(13)
memory usage: 1.2+ MB

In [196]:
df_cleaned2

,PatientID,AdmissionDate,DischargeDate,Diagnosis,Treatment,Doctor,Department,Age,Gender,BloodType,Medication,TestResults,BillingAmount,InsuranceProvider,AppointmentDate
0,PT_001,10-03-2024,05-11-2025,Appendicitis,"Special with job,",Carl Beard,Orthopedics,81,Female,B+,Unknown/Undifined,85/67,9495.73,Unknown/Undifined,17-02-2024
1,PT_K_2,27-06-2023,12-05-2023,Fracture,"Certainly way ten,",Mary Sanchez,Endocrinology,88,Male,O-,civil,140/118,8681.08,HC Insurance,08-08-2023
2,PT_003,18-05-2024,29-04-2025,Appendicitis,"Study small,",Mr. Patrick Harris MD,Orthopedics,94,Male,O-,word,92/95,2829.42,Unknown/Undifined,21-05-2024
3,PT_004,11-03-1978,26-10-2019,COPD,"Investment human,",Donald Roach,Endocrinology,26,Female,A+,Unknown/Undifined,140/119,1121.27,Unknown/Undifined,11-03-2024
4,PT_005,23-11-2024,12-02-2024,Diabetes,"Every coach,",Unknown/Undifined,Orthopedics,35,Female,B-,Unknown/Undifined,71/68,5555.75,HC Insurance,14-11-2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10295,PT_691,16-03-2024,Unknown/Undifined,COPD,"Focus population green,",Jennifer Rodriguez,Cardiology,68,Female,O+,step,High,5014.95,HealthPlus,21-04-2024
10296,PT_7247,29-03-2023,27-10-2024,Fracture,"Hold,",Christine Morris,Orthopedics,15,Female,O-,floor 1 units,98/68,8152.91,Unknown/Undifined,14-12-2023
10297,PT_4814,11-10-1998,22-04-2005,Fracture,"Imagine power PM,",Luis May,Endocrinology,3,Male,A+,senior,181/80,2323.13,Unknown/Undifined,13-06-2024
10298,PT_8633,02-01-2024,28-11-2024,Diabetes,"Morning body than,",Jamie King,Cardiology,52,Male,AB+,Unknown/Undifined,169/46,3466.39,HealthPlus,26-06-2024
10299,PT_2977,31-03-2017,02-01-2018,COPD,"Notice after staff,",Thomas Perry,Cardiology,89,Unknown/Undifined,A+,edge,72/46,5592.93,MediCare,24-01-2024

# Prepo Government

In [197]:
government.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10500 entries, 0 to 10499
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CitizenID        10500 non-null  object
 1   Name             10500 non-null  object
 2   BirthDate        10500 non-null  object
 3   Nationality      10500 non-null  object
 4   Address          10500 non-null  object
 5   VotingStatus     10500 non-null  object
 6   PassportNumber   10500 non-null  object
 7   TaxID            9418 non-null   object
 8   MaritalStatus    10500 non-null  object
 9   CriminalRecord   8407 non-null   object
 10  EducationLevel   10500 non-null  object
 11  Income           10500 non-null  float64
 12  ImmigrationYear  2607 non-null   float64
dtypes: float64(2), object(11)
memory usage: 1.0+ MB

In [198]:
government.isna().sum()

CitizenID             0
Name                  0
BirthDate             0
Nationality           0
Address               0
VotingStatus          0
PassportNumber        0
TaxID              1082
MaritalStatus         0
CriminalRecord     2093
EducationLevel        0
Income                0
ImmigrationYear    7893
dtype: int64

In [199]:
government['TaxID'] = government['TaxID'].fillna("Unknown/None")
government['CriminalRecord'] = government['CriminalRecord'].fillna("Unknown/None")
government['ImmigrationYear'] = government['ImmigrationYear'].fillna("Unknown/None")
government['Name'] = government['Name'].str.title()

In [200]:
def fix_date(date):
        try:
            return pd.to_datetime(date, infer_datetime_format=True, dayfirst=True).strftime('%d-%m-%Y')
        except Exception:
            return None
        
government['BirthDate'] = government['BirthDate'].apply(fix_date)

C:\Users\Faiz Iqbal\AppData\Local\Temp\ipykernel_32284\1383829374.py:3: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  return pd.to_datetime(date, infer_datetime_format=True, dayfirst=True).strftime('%d-%m-%Y')
C:\Users\Faiz Iqbal\AppData\Local\Temp\ipykernel_32284\1383829374.py:3: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(date, infer_datetime_format=True, dayfirst=True).strftime('%d-%m-%Y')

In [201]:
government['Nationality'].value_counts()

Nationality
FRANCE           1212
France           1205
India            1205
IND              1164
Bharat           1156
FR               1135
USA               902
America           867
US                848
United States     806
Name: count, dtype: int64

In [202]:
government['Nationality'] = government['Nationality'].apply(
    lambda x: "France" if str(x).strip().lower() in ["france", "fr"] else
                "India" if str(x).strip().lower() in ["india", "ind", "bharat"] else 
                "United States" if str(x).strip().lower() in ["usa", "us", "america", "united states"] else x)

In [203]:
government['VotingStatus'] = government['VotingStatus'].apply(
    lambda x: "Yes" if str(x).strip().lower() in ["yes", "y", "registered"] else
                "No" if str(x).strip().lower() in ["no", "n"] else 
                "Unknown" if str(x).strip().lower() in [""] else "Unknown")

In [204]:
government['EducationLevel'] = government['EducationLevel'].apply(
    lambda x: "High School" if str(x).strip().lower() in ["high school", "hs"] else x)

In [205]:
government['MaritalStatus'] = government['MaritalStatus'].apply(
    lambda x: "Single" if str(x).strip().lower() in ["single", "s"] else x)

In [206]:
government['CriminalRecord'] = government['CriminalRecord'].apply(
    lambda x: "Yes" if str(x).strip().lower() in ["yes"] else
                "No" if str(x).strip().lower() in ["no"] else 
                "Pending" if str(x).strip().lower() in ["pending"] else "Unknown/None")

In [207]:
import re
from sklearn.impute import KNNImputer

def preprocess_data3(df):
    
    def fix_date(date):
        try:
            return pd.to_datetime(date, infer_datetime_format=True, dayfirst=True).strftime('%d-%m-%Y')
        except Exception:
            return "Unknown"

    df['BirthDate'] = df['BirthDate'].apply(fix_date)

    df['TaxID'] = df['TaxID'].fillna("Unknown/None")
    df['CriminalRecord'] = df['CriminalRecord'].fillna("Unknown/None")
    df['ImmigrationYear'] = df['ImmigrationYear'].fillna("Unknown/None")
    df['Name'] = df['Name'].str.title()

    df['Nationality'] = df['Nationality'].apply(
    lambda x: "France" if str(x).strip().lower() in ["france", "fr"] else
                "India" if str(x).strip().lower() in ["india", "ind", "bharat"] else 
                "United States" if str(x).strip().lower() in ["usa", "us", "america", "united states"] else x)
    
    df['VotingStatus'] = df['VotingStatus'].apply(
    lambda x: "Yes" if str(x).strip().lower() in ["yes", "y", "registered"] else
                "No" if str(x).strip().lower() in ["no", "n"] else 
                "Unknown" if str(x).strip().lower() in [""] else "Unknown")
    
    df['CriminalRecord'] = df['CriminalRecord'].apply(
    lambda x: "Yes" if str(x).strip().lower() in ["yes"] else
                "No" if str(x).strip().lower() in ["no"] else 
                "Pending" if str(x).strip().lower() in ["pending"] else "Unknown/None")
    
    df['MaritalStatus'] = df['MaritalStatus'].apply(
    lambda x: "Single" if str(x).strip().lower() in ["single", "s"] else x)
    
    df['EducationLevel'] = df['EducationLevel'].apply(
    lambda x: "High School" if str(x).strip().lower() in ["high school", "hs"] else x)

    return df

# Preprocess data
df_cleaned3 = preprocess_data3(government)

# Display first few rows after preprocessing
df_cleaned3.info()

C:\Users\Faiz Iqbal\AppData\Local\Temp\ipykernel_32284\2048438891.py:8: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  return pd.to_datetime(date, infer_datetime_format=True, dayfirst=True).strftime('%d-%m-%Y')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10500 entries, 0 to 10499
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CitizenID        10500 non-null  object
 1   Name             10500 non-null  object
 2   BirthDate        10500 non-null  object
 3   Nationality      10500 non-null  object
 4   Address          10500 non-null  object
 5   VotingStatus     10500 non-null  object
 6   PassportNumber   10500 non-null  object
 7   TaxID            10500 non-null  object
 8   MaritalStatus    10500 non-null  object
 9   CriminalRecord   10500 non-null  object
 10  EducationLevel   10500 non-null  object
 11  Income           10500 non-null  float64
 12  ImmigrationYear  10500 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.0+ MB

In [208]:
df_cleaned3

,CitizenID,Name,BirthDate,Nationality,Address,VotingStatus,PassportNumber,TaxID,MaritalStatus,CriminalRecord,EducationLevel,Income,ImmigrationYear
0,CIT_001,Allen Novak,16-06-1968,United States,"597 Carr Creek Apt. 464; West Andrew; NE 76236,",No,460200468,Unknown/None,Married,No,High School,42533.54,Unknown/None
1,CIT_002,Tamara Ramsey,02-11-1987,France,"3899 Medina Roads; Crystaltown; NY 04112,",No,INVALID_our,TAX-002-36,Single,No,Masters,28175.78,Unknown/None
2,CIT_003,David Williams,15-12-1937,India,"03064 Eric Ferry; Port Rebecca; AZ 09961,",Yes,E48182721,TAX-003-03,Widowed,Unknown/None,High School,143299.35,1986.0
3,CIT_004,Desiree Willis,24-03-1991,United States,"773 Perry Flats; East Michael; WY 77221,",Yes,O98365870,TAX_004_11,Married,No,Doctorate,105629.33,Unknown/None
4,CIT_005,Terry Gill,15-10-2000,France,"214 Michael Crescent Suite 393, New Paulport, ...",No,R72171677,TAX-005-00,Single,Pending,PhD,117985.07,2005.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10495,CIT_3673,Scott Barrett,03-08-1950,India,"10041 Fisher Row Suite 135, Lake Anneburgh, GA...",No,407208444,Unknown/None,Unknown,Unknown/None,PhD,99415.01,Unknown/None
10496,CIT_8693,James Brown,13-12-2000,United States,"563 Romero Ferry, Petersonport, OR 06511",No,983829316,TAX-8693-20,Unknown,Unknown/None,PhD,128327.81,Unknown/None
10497,CIT_7140,Susan Beck,05-11-2001,United States,"31275 Michelle Well Suite 725, West Randytown,...",Unknown,INVALID_enjoy,TAX-7140-50,Single,Yes,High School,26909.17,Unknown/None
10498,CIT_779,Jackson Stout,18-08-1983,India,"10300 Michelle Passage, Amandaburgh, RI 93986",Yes,O91186652,TAX-779-15,Single,No,High School,132278.13,1969.0
10499,CIT_2923,Dawn Lane,23-12-2002,United States,"07158 Tamara Drives Apt. 970, Brooksfurt, CT 3...",No,S29245729,TAX-2923-67,Married,Yes,PhD,52938.39,Unknown/None

# Cek Hasil

In [209]:
custdirty_clean = pd.read_csv("C:/Uner/Semester 4/Data Mining I/Week 3/custdirty_data_cleaned.csv")

In [210]:
custdirty_clean

,ID,CustomerID,Product_Category,Purchase_Date,Price,Quantity,Product_Description,Country,Phone_Number,Email
0,1,CUST_1,Electronics,05-03-2024,65.58,11,"Today, federal, claim, report, consider, publi...",United States,2505181271,eric82@example.com
1,2,CUST_2,Electronics,29-05-2024,335.85,1,Alone appear example.,Canada,Unknown/Invalid Format,allentodd@example.org
2,3,CUST_3,Electronics,28-05-2024,106.92,19,"DIRECTION, SECURITY, WHO, GROUND, TRIP, ROOM. ...",United Kingdom,Unknown/Invalid Format,oschultz@example.com
3,4,CUST_4,Clothing,30-06-2024,389.70,6,"Answer, huge, six, new, tough. - picture",Canada,Unknown/Invalid Format,ajohnson@example.org
4,5,CUST_5,Furniture,14-10-2024,140.78,14,Recent last economic establish understand.,Canada,2942836286,andersonsheriexample.org.
...,...,...,...,...,...,...,...,...,...,...
10295,7431,CUST_7431,Furniture,24-02-2024,445.08,6,"Meeting, adult, choose, customer, see, base. -...",United States,Unknown/Invalid Format,erinleon@example.net
10296,940,CUST_940,Clothing,13-06-2024,188.90,9,Actually home blue get.,United States,Unknown/Invalid Format,obrienmichael@example.org
10297,9519,CUST_9519,Clothing,04-04-2024,371.88,10,Option stand determine course include.,United States,4348959812,brownjames@example.net
10298,1804,CUST_1804,Books,06-05-2024,165.60,18,"ACCOUNT, AFFECT, NIGHT. - ATTACK",Canada,8682519899,thomas86@example.com
10299,8721,CUST_8721,Clothing,08-12-2024,90.66,4,"Fall, task, vote, remain, my, score. - toward",United States,Unknown/Invalid Format,kyle30@example.org

In [211]:
hospital_clean = pd.read_csv("C:/Uner/Semester 4/Data Mining I/Week 3/hospital_data_dirty_cleaned.csv")

In [212]:
hospital_clean

,PatientID,AdmissionDate,DischargeDate,Diagnosis,Treatment,Doctor,Department,Age,Gender,BloodType,Medication,TestResults,BillingAmount,InsuranceProvider,AppointmentDate
0,PT_001,10-03-2024,05-11-2025,Appendicitis,"Special with job,",Carl Beard,Orthopedics,81,Female,B+,Unknown/Undifined,85/67,9495.73,Unknown/None,17-02-2024
1,PT_K_2,27-06-2023,12-05-2023,Fracture,"Certainly way ten,",Mary Sanchez,Endocrinology,88,Male,O-,civil,140/118,8681.08,HC Insurance,08-08-2023
2,PT_003,18-05-2024,29-04-2025,Appendicitis,"Study small,",Mr. Patrick Harris MD,Orthopedics,94,Male,O-,word,92/95,2829.42,Unknown/None,21-05-2024
3,PT_004,11-03-1978,26-10-2019,COPD,"Investment human,",Donald Roach,Endocrinology,26,Female,A+,Unknown/Undifined,140/119,1121.27,Unknown/None,11-03-2024
4,PT_005,23-11-2024,12-02-2024,Diabetes,"Every coach,",Unknown/Undifined,Orthopedics,35,Female,B-,Unknown/Undifined,71/68,5555.75,HC Insurance,14-11-2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10295,PT_691,16-03-2024,Unknown/Invalid Format,COPD,"Focus population green,",Jennifer Rodriguez,Cardiology,68,Female,O+,step,High,5014.95,HealthPlus,21-04-2024
10296,PT_7247,29-03-2023,27-10-2024,Fracture,"Hold,",Christine Morris,Orthopedics,15,Female,O-,floor 1 units,98/68,8152.91,Unknown/None,14-12-2023
10297,PT_4814,11-10-1998,22-04-2005,Fracture,"Imagine power PM,",Luis May,Endocrinology,3,Male,A+,senior,181/80,2323.13,Unknown/None,13-06-2024
10298,PT_8633,02-01-2024,28-11-2024,Diabetes,"Morning body than,",Jamie King,Cardiology,52,Male,AB+,Unknown/Undifined,169/46,3466.39,HealthPlus,26-06-2024
10299,PT_2977,31-03-2017,02-01-2018,COPD,"Notice after staff,",Thomas Perry,Cardiology,89,Unknown/Undifined,A+,edge,72/46,5592.93,MediCare,24-01-2024

In [213]:
government_clean = pd.read_csv("C:/Uner/Semester 4/Data Mining I/Week 3/government_citizenship_dirty_cleaned.csv")

In [214]:
government_clean

,CitizenID,Name,BirthDate,Nationality,Address,VotingStatus,PassportNumber,TaxID,MaritalStatus,CriminalRecord,EducationLevel,Income,ImmigrationYear
0,CIT_001,Allen Novak,16-06-1968,United States,"597 Carr Creek Apt. 464; West Andrew; NE 76236,",No,460200468,Unknown/None,Married,No,High School,42533.54,Unknown/None
1,CIT_002,Tamara Ramsey,02-11-1987,France,"3899 Medina Roads; Crystaltown; NY 04112,",No,INVALID_our,TAX-002-36,Single,No,Masters,28175.78,Unknown/None
2,CIT_003,David Williams,15-12-1937,India,"03064 Eric Ferry; Port Rebecca; AZ 09961,",Yes,E48182721,TAX-003-03,Widowed,Unknown/None,High School,143299.35,1986.0
3,CIT_004,Desiree Willis,24-03-1991,United States,"773 Perry Flats; East Michael; WY 77221,",Yes,O98365870,TAX_004_11,Married,No,Doctorate,105629.33,Unknown/None
4,CIT_005,Terry Gill,15-10-2000,France,"214 Michael Crescent Suite 393, New Paulport, ...",No,R72171677,TAX-005-00,Single,Pending,PhD,117985.07,2005.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10495,CIT_3673,Scott Barrett,03-08-1950,India,"10041 Fisher Row Suite 135, Lake Anneburgh, GA...",No,407208444,Unknown/None,Unknown,Unknown/None,PhD,99415.01,Unknown/None
10496,CIT_8693,James Brown,13-12-2000,United States,"563 Romero Ferry, Petersonport, OR 06511",No,983829316,TAX-8693-20,Unknown,Unknown/None,PhD,128327.81,Unknown/None
10497,CIT_7140,Susan Beck,05-11-2001,United States,"31275 Michelle Well Suite 725, West Randytown,...",Unknown,INVALID_enjoy,TAX-7140-50,Single,Yes,High School,26909.17,Unknown/None
10498,CIT_779,Jackson Stout,18-08-1983,India,"10300 Michelle Passage, Amandaburgh, RI 93986",Yes,O91186652,TAX-779-15,Single,No,High School,132278.13,1969.0
10499,CIT_2923,Dawn Lane,23-12-2002,United States,"07158 Tamara Drives Apt. 970, Brooksfurt, CT 3...",No,S29245729,TAX-2923-67,Married,Yes,PhD,52938.39,Unknown/None